name = "applied-practical-thinking"
<<<<<<< Updated upstream
<<<<<<< Updated upstream
type = "javascript"
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
main = "src/index.ts"
compatibility_date = "2026-01-19"
